sonar.projectKey=renault-test
sonar.projectName=Renault Test Project
sonar.projectVersion=1.0

# Backend ve Frontend src klasörlerini virgülle belirtin
sonar.sources=backend/src,frontend/src

# Dışlanacak klasörler (node_modules, build çıktıları, test dosyaları)
sonar.exclusions=**/node_modules/**,**/dist/**,**/.angular/**,**/*.spec.ts,**/*.test.ts

sonar.sourceEncoding=UTF-8
sonar.host.url=http://localhost:9000
