version: '3.8'

services:
  openldap:
    image: osixia/openldap:1.5.0
    container_name: local-openldap
    environment:
      LDAP_ORGANISATION: "Sirketim"
      LDAP_DOMAIN: "sirket.com"
      LDAP_ADMIN_PASSWORD: "adminpassword"
    ports:
      - "389:389"
      - "636:636"

  phpldapadmin:
    image: osixia/phpldapadmin:0.9.0
    container_name: local-phpldapadmin
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: "openldap"
      PHPLDAPADMIN_HTTPS: "false"
    ports:
      - "8080:80"
    depends_on:
      - openldap